name: CI

on:
  push:
    branches: [main, dev, anthony]
  pull_request:
    branches: [main, dev, anthony]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run autoflake
        run: poetry run autoflake --remove-all-unused-imports --remove-unused-variables --in-place --expand-star-imports -r .

      - name: Run isort
        run: poetry run isort .

      - name: Run autopep8
        run: poetry run autopep8 --in-place --recursive --max-line-length=120 .

      - name: Run black
        run: poetry run black .

      - name: Run flake8
        run: poetry run flake8

      - name: Run tests
        run: poetry run pytest
